"use client";

import { ChevronDown, Copy, Download, Filter, MoreHorizontal, Search, UserPlus } from "lucide-react";
import { useMemo, useState } from "react";
import type { DashboardRegistration } from "@/lib/data/courses";

export function RegistrationsTable({ registrations }: { registrations: DashboardRegistration[] }) {
  const [query, setQuery] = useState("");
  const [course, setCourse] = useState("all");
  const [status, setStatus] = useState("all");
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const courses = useMemo(() => [...new Set(registrations.map((item) => item.course).filter(Boolean))], [registrations]);
  const filtered = useMemo(() => registrations.filter((person) => { const haystack = `${person.name} ${person.email} ${person.phone}`.toLowerCase(); return (!query || haystack.includes(query.toLowerCase())) && (course === "all" || person.course === course) && (status === "all" || person.status === status); }), [registrations, query, course, status]);
  const downloadCsv = () => { const rows = [["name", "email", "phone", "course", "status", "registered_at"], ...filtered.map((person) => [person.name, person.email, person.phone, person.course, person.status, person.registeredAt])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "fiper-registrations.csv"; link.click(); URL.revokeObjectURL(url); };
  return <>
    <div className="flex gap-2"><button type="button" onClick={() => window.alert("يمكنك إضافة التسجيل اليدوي من خلال نموذج التسجيل العام.")} className="flex h-11 items-center gap-2 rounded-xl border border-[#dce5eb] bg-white px-4 text-[9px] font-bold text-[#536b7b]"><UserPlus size={15} /> إضافة يدوية</button><button type="button" onClick={downloadCsv} className="flex h-11 items-center gap-2 rounded-xl bg-[#102f47] px-4 text-[9px] font-bold text-white"><Download size={15} /> تصدير CSV</button></div>
    <section className="mt-5 overflow-hidden rounded-[22px] border border-[#dfe7ec] bg-white">
      <div className="flex flex-col gap-3 border-b border-[#e8eef2] p-4 sm:flex-row sm:items-center sm:p-5"><div className="relative flex-1"><Search size={15} className="absolute right-4 top-1/2 -translate-y-1/2 text-[#8ba0ae]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="الاسم، البريد أو الهاتف..." className="h-11 w-full rounded-xl border border-[#dfe7ec] bg-[#f8fafb] pr-10 pl-4 text-[10px] focus:border-[#9ebfd5] focus:outline-none" /></div><label className="relative"><span className="sr-only">الدورة</span><select value={course} onChange={(event) => setCourse(event.target.value)} className="h-11 appearance-none rounded-xl border border-[#dfe7ec] bg-white px-4 pl-9 text-[9px] font-bold text-[#617585]"><option value="all">كل الدورات</option>{courses.map((item) => <option key={item} value={item}>{item}</option>)}</select><ChevronDown size={13} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2" /></label><label className="relative"><span className="sr-only">الحالة</span><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 appearance-none rounded-xl border border-[#dfe7ec] bg-white px-4 pl-9 text-[9px] font-bold text-[#617585]"><option value="all">كل الحالات</option>{[...new Set(registrations.map((item) => item.status))].map((item) => <option key={item} value={item}>{item}</option>)}</select><Filter size={13} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2" /></label></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-right"><thead className="bg-[#f8fafb] text-[9px] font-semibold text-[#7f929f]"><tr><th className="px-3 py-3">المشارك</th><th className="px-3 py-3">رقم واتساب</th><th className="px-3 py-3">الدورة</th><th className="px-3 py-3">المصدر</th><th className="px-3 py-3">الحالة</th><th className="px-3 py-3">التسجيل</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-[#edf2f5]">{filtered.length ? filtered.map((person) => <tr key={person.id} className="text-[9px] transition hover:bg-[#fbfcfd]"><td className="px-3 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edf4f8] text-[9px] font-bold text-[#315a75]">{person.name.split(" ").map((part) => part[0]).join("")}</span><span><strong className="block text-[10px]">{person.name}</strong><small className="latin mt-1 block text-[8px] text-[#8da0ad]">{person.email}</small></span></div></td><td className="latin px-3 py-4 text-[#607686]">{person.phone}</td><td className="px-3 py-4 text-[#607686]">{person.course}</td><td className="latin px-3 py-4 text-[#607686]">{person.source}</td><td className="px-3 py-4"><span className={`rounded-full px-3 py-1.5 text-[8px] font-bold ${person.status === "مؤكد" ? "bg-[#eaf8f3] text-[#168a65]" : "bg-[#fff6df] text-[#a36b00]"}`}>{person.status}</span></td><td className="px-3 py-4 text-[#8da0ad]">{person.time}</td><td className="relative px-5 py-4"><button type="button" aria-label="خيارات" onClick={() => setOpenMenu(openMenu === person.id ? null : person.id)} className="text-[#8598a6]"><MoreHorizontal size={17} /></button>{openMenu === person.id && <div className="absolute left-4 top-12 z-20 w-36 rounded-xl border border-[#dce5eb] bg-white p-1 text-right shadow-lg"><button type="button" onClick={() => { void navigator.clipboard?.writeText(person.email); setOpenMenu(null); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-[9px] hover:bg-[#f4f8fa]"><Copy size={13} /> نسخ البريد</button></div>}</td></tr>) : <tr><td colSpan={7} className="px-6 py-14 text-center text-xs text-[#788d9c]">لا توجد نتائج مطابقة.</td></tr>}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-[#e8eef2] px-5 py-4 text-[9px] text-[#8295a2]"><span>عرض {filtered.length} من {registrations.length}</span><span className="text-[#1574ad]">الفلترة مفعلة مباشرة</span></div>
    </section>
  </>;
}