import { Clock3, Download, RefreshCw, UserRoundCheck, UserRoundX } from "lucide-react";
import { AttendanceTable } from "@/components/dashboard/attendance-table";
import { getDashboardAttendance } from "@/lib/data/dashboard";

export default async function AttendancePage() {
  const data = await getDashboardAttendance();
  const eligible = data.attended + data.absent;
  const stats = [["الحاضرون", String(data.attended), eligible ? `${Math.round((data.attended / eligible) * 100)}% من الحضور المسجل` : "لا توجد بيانات", UserRoundCheck, "bg-[#eaf8f3] text-[#168a65]"], ["لم يحضروا", String(data.absent), eligible ? `${Math.round((data.absent / eligible) * 100)}% بعد بدء الدورة` : `${data.pending} بانتظار بدء الدورة`, UserRoundX, "bg-[#fff0f1] text-[#C32828]"], ["متوسط الحضور", `${data.averageMinutes} دقيقة`, "من بيانات جلسات الحضور", Clock3, "bg-[#eaf5fc] text-[#1574ad]"]] as const;
  return <div className="mx-auto max-w-[1450px]"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold text-[#C32828]">Google Meet</p><h1 className="mt-2 text-2xl font-bold tracking-[-0.035em] sm:text-3xl">الحضور</h1><p className="mt-2 text-xs text-[#788d9c]">مزامنة الحضور ومدة المشاركة مع إمكانية التصحيح اليدوي.</p></div><div className="flex gap-2"><button type="button" className="flex h-11 items-center gap-2 rounded-xl border border-[#dce5eb] bg-white px-4 text-[9px] font-bold text-[#536b7b]"><RefreshCw size={14} /> مزامنة Meet</button><button type="button" className="flex h-11 items-center gap-2 rounded-xl bg-[#102f47] px-4 text-[9px] font-bold text-white"><Download size={14} /> تصدير</button></div></div><div className="mt-7 grid gap-4 sm:grid-cols-3">{stats.map(([label, value, note, Icon, tone]) => <div key={label} className="flex items-center gap-4 rounded-[18px] border border-[#dfe7ec] bg-white p-5"><span className={`flex h-11 w-11 items-center justify-center rounded-[14px] ${tone}`}><Icon size={19} /></span><span><small className="text-[9px] text-[#7f929f]">{label}</small><strong className="mt-1 block text-xl">{value}</strong><small className="text-[8px] text-[#91a2ae]">{note}</small></span></div>)}</div><AttendanceTable rows={data.rows} /></div>;
}